### ISSUE TITLE
Clean up the top-level directory?

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13prebuilt#17]
Before we hard-wired versions in (at 1.1.25, then 1.1.39, now 1.1.57) we dropped binaries at the top-level.  They are from 1.1.19 and it is a little ... out of kilter. 

They are six-years old.  Nobody is going to use the build script with their path.  Shall we just delete top-level directories linux, osx. windows?  Or, if we want to keep the binaries, show them into v1.1.19?

Or does none of this matter as it is only important that we keep once published binaries?

**Comment by christophsax** [comment]
Since we have them, I would vote to put them in a folder `v1.1.19`, even if this does not work with the early version of x13binary. There may be a very exotic use-case where someone wants to use this version, so they can still use them and manually link to them from seasonal.

At the same time, I think it makes sense to clean up the top-level directory. These folders are confusing.

**Comment by eddelbuettel** [comment]
I lean the same way of 'rather keeping them' (even if "one day" we may bump up against GitHub's repo size limit, we can then switch to a suffix -2 or whatnot) so I'll make that change.

I think they are all 1.1.19 -- at least the Linux version I can still run is:

```sh
edd@rob:~/git/x13prebuilt(master)$ linux/64/x13ashtml --version

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 19
 Execution began  Aug  1, 2021  08.11.43 

 ERROR: Program option --version not defined.  Valid program options are 
        -I, -O, -M, -D, -C, -P, -W, -S, -N, -V, -R, -Q.
edd@rob:~/git/x13prebuilt(master)$ 
```

so I prepare a PR with a move into that dir.
